FROM ubuntu:20.04

ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && \
    apt-get install -yq --no-install-recommends python3-pip \
        build-essential \
        libopencv-dev \
        python3-dev \
        wget \
        git  \
        tzdata && apt-get upgrade -y && apt-get clean

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN pip install --upgrade pip
RUN pip install --no-cache-dir numpy==1.19.5 \
    opencv-python==4.5.5.64 \
    transformers==4.16.2 \
    diffusers==0.2.4 \
    tqdm==4.64.0 \
    openvino==2022.1.0 \
    huggingface_hub==0.9.0 \
    scipy==1.9.0 \
    streamlit==1.12.0 \
    watchdog==2.1.9 \
    sagemaker-training
RUN git clone https://github.com/bes-dev/stable_diffusion.openvino
WORKDIR /stable_diffusion.openvino

# Download resources
RUN python -c "from stable_diffusion_engine import StableDiffusionEngine; StableDiffusionEngine(None)"